import fs from 'fs';

const BATCH1 = `Microsoft Learn,Azure,Cloud Fundamentals,Azure architecture,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Cloud Fundamentals,Subscriptions,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Cloud Fundamentals,Resource groups,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Cloud Fundamentals,Identity,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Cloud Fundamentals,Governance,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Cloud Fundamentals,Cost management,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Compute,Azure Virtual Machines,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Compute,App Service,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Compute,Azure Functions,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Compute,Container Apps,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Compute,AKS,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Storage & Databases,Blob Storage,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Storage & Databases,Azure Files,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Storage & Databases,Azure SQL,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Storage & Databases,Cosmos DB,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Storage & Databases,PostgreSQL on Azure,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,Virtual Network,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,Load Balancer,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,Application Gateway,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,VPN Gateway,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,ExpressRoute,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Networking,DNS,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Security,Microsoft Defender for Cloud,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Security,Microsoft Sentinel,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Security,Key Vault,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Security,Entra ID,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Security,Zero Trust,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Azure Data Factory,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Synapse Analytics,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Microsoft Fabric,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Azure Machine Learning,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Azure AI Foundry,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,Data & AI,Azure OpenAI,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,Azure DevOps,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,Azure Pipelines,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,Bicep,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,ARM templates,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,GitHub Actions,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Azure,DevOps,Infrastructure as code,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Productivity,Teams,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Productivity,SharePoint,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Productivity,OneDrive,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Productivity,Exchange Online,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Productivity,Microsoft 365 Apps,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Administration,Tenant administration,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Administration,Identity and access,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Administration,Endpoint management,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Administration,Intune,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Administration,Compliance,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Copilot,Microsoft 365 Copilot,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Copilot,Copilot adoption,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Copilot,Prompting,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Microsoft 365,Copilot,Copilot agents,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Low Code,Power Apps,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Low Code,Power Automate,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Low Code,Power Pages,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Low Code,Dataverse,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Low Code,Copilot Studio,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Analytics,Power BI,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Analytics,DAX,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Analytics,Power Query,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Analytics,Data modeling,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Power Platform,Analytics,Dashboards,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Dynamics 365 Sales,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Customer Service,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Field Service,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Finance,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Supply Chain Management,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Dynamics 365,Business Applications,Business Central,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,C#,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,.NET,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,ASP.NET Core,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,Blazor,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,Entity Framework Core,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,.NET,MAUI,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,GitHub,GitHub Foundations,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,GitHub,GitHub Actions,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,GitHub,GitHub Advanced Security,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,GitHub,GitHub Copilot,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,Developer Tools,Visual Studio,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,Developer Tools,Visual Studio Code,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,Developer Tools,Windows development,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Developer Platform,Developer Tools,PowerShell,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Security,Security operations,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Security,Identity protection,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Security,Information protection,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Security,Threat hunting,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Security,Cloud security,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Compliance,Microsoft Purview,Tool / Platform,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Compliance,Data governance,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Compliance,eDiscovery,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
Microsoft Learn,Security & Compliance,Compliance,Insider risk management,Skill / Topic,Varies,"Modules, learning paths, instructor-led courses, sandboxes, certifications",https://learn.microsoft.com/training/,46225,Catalog-level coverage; verify individual offerings on portal.
`;

fs.appendFileSync('./data/mapit-study-portal-catalog.csv', BATCH1);
console.log('Appended batch 1 successfully!');
