import fs from 'fs';

const CSV_ROWS = `Portal,Domain,Topic,Detailed Skill / Tool,Type,Level,Learning Format,Official Source URL,Verified Date,Notes
W3Schools,Web Development,HTML,Semantic HTML,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Forms,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Tables,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Media,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Canvas,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,SVG,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Accessibility basics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,HTML,Web APIs,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Selectors,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Box model,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Flexbox,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,CSS Grid,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Responsive design,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Animations,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Transforms,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,CSS,Sass,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Syntax,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,DOM,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Events,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Async JavaScript,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Promises,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Fetch API,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,JSON,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,JavaScript,Web storage,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,React,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,Angular,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,AngularJS,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,Vue,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,jQuery,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,Bootstrap,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Frameworks & Libraries,W3.CSS,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Backend Web,Node.js,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Backend Web,PHP,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Backend Web,ASP.NET,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Web Development,Backend Web,Django,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Python,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Java,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,C,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,C++,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,C#,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,R,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Go,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Kotlin,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Swift,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Rust,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,TypeScript,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Languages,Bash,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Variables,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Control flow,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Functions,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Object-oriented programming,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Data structures,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Programming,Programming Foundations,Algorithms,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,SQL,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,MySQL,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,PostgreSQL,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,MongoDB,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,Database design,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,Queries,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,Joins,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Databases,Stored procedures,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,NumPy,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,Pandas,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,SciPy,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,Matplotlib,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,Statistics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,Data cleaning,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Data Science,Machine learning basics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Business Tools,Excel formulas,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Business Tools,Excel functions,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Business Tools,Excel charts,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Data & Databases,Business Tools,Excel data analysis,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Cloud,AWS fundamentals,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Cloud,AWS compute,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Cloud,AWS storage,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Cloud,AWS databases,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Cloud,AWS development tools,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",AI,Artificial intelligence fundamentals,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",AI,Generative AI,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",AI,Machine learning workflow,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",AI,Prompting basics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Security,Cybersecurity fundamentals,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Security,Web security,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Security,Password security,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,"Cloud, AI & Security",Security,Network security basics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Version Control,Git,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Version Control,GitHub,Tool / Platform,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Version Control,Branches,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Version Control,Merging,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Version Control,Pull requests,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Developer Workflow,Code editors,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Developer Workflow,Command line,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Developer Workflow,Package managers,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Developer Workflow,Web hosting,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
W3Schools,Developer Tools,Developer Workflow,Deployment basics,Skill / Topic,Varies,"Tutorials, references, exercises, quizzes, code editor",https://www.w3schools.com/tutorials/,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Arrays,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Linked lists,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Stacks,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Queues,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Trees,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Graphs,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Heaps,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Hashing,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Data Structures,Tries,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Sorting,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Searching,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Greedy algorithms,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Dynamic programming,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Backtracking,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,Graph algorithms,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Algorithms,String algorithms,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,Operating systems,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,Computer networks,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,DBMS,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,Object-oriented design,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,Computer organization,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Computer Science Foundations,Core CS,Theory of computation,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,C,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,C++,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,Java,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,Python,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,JavaScript,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,C#,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,Go,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,Kotlin,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Languages,Rust,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Competitive Programming,Complexity analysis,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Competitive Programming,Problem solving,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Competitive Programming,Contest strategy,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Programming,Competitive Programming,Mathematics for coding,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,HTML,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,CSS,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,JavaScript,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,React,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,Angular,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,Bootstrap,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Frontend,Responsive design,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,Node.js,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,Express,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,Django,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,Flask,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,Spring Boot,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Backend,REST APIs,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Full Stack,MERN stack,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Full Stack,MEAN stack,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Full Stack,Authentication,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Full Stack,Databases,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Full Stack,Deployment,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Mobile,Android,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Mobile,Kotlin Android,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Mobile,Flutter,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Web & Mobile Development,Mobile,React Native,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Data Science,Python for data science,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Data Science,Statistics,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Data Science,Data cleaning,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Data Science,Exploratory data analysis,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Data Science,Data visualization,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Machine Learning,Supervised learning,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Machine Learning,Unsupervised learning,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Machine Learning,Feature engineering,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Machine Learning,Model evaluation,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Machine Learning,Scikit-learn,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,Neural networks,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,TensorFlow,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,Keras,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,PyTorch,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,Computer vision,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Deep Learning,NLP,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Generative AI,Large language models,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Generative AI,Prompt engineering,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Generative AI,RAG,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Generative AI,AI agents,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Generative AI,Vector databases,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Analytics,SQL,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Analytics,Excel,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Analytics,Power BI,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Analytics,Tableau,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Data, AI & Analytics",Analytics,Business analytics,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cloud,AWS,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cloud,Azure,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cloud,Google Cloud,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cloud,Cloud architecture,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cloud,Serverless,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Linux,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Git,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Docker,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Kubernetes,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,CI/CD,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Jenkins,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Terraform,Tool / Platform,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",DevOps,Ansible,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cybersecurity,Ethical hacking,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cybersecurity,Network security,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cybersecurity,Web security,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cybersecurity,Cryptography,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,"Cloud, DevOps & Security",Cybersecurity,Security operations,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,Low-level design,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,High-level design,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,Scalability,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,Caching,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,Distributed systems,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,System Design,Microservices,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Testing,Manual testing,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Testing,Automation testing,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Testing,Selenium,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Testing,API testing,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Interview Preparation,Coding interviews,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Interview Preparation,System design interviews,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Interview Preparation,Aptitude,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Interview Preparation,Resume preparation,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
GeeksforGeeks,Software Engineering & Careers,Interview Preparation,Placement preparation,Skill / Topic,Varies,"Articles, tutorials, practice problems, courses, contests, interview preparation",https://www.geeksforgeeks.org/courses,46225,Catalog-level coverage; verify individual offerings on portal.
`;

if (!fs.existsSync('./data')) {
  fs.mkdirSync('./data', { recursive: true });
}
fs.writeFileSync('./data/mapit-study-portal-catalog.csv', CSV_ROWS);
console.log('Saved baseline CSV successfully!');
